language: node_js
node_js: stable
dist: trusty
sudo: false
install:
  - npm install --production
script:
  - npm run $RESPONSE_TYPE
env:
  - RESPONSE_TYPE=code
  - RESPONSE_TYPE=id_token
  - RESPONSE_TYPE=id_token+token
  - RESPONSE_TYPE=code+id_token
  - RESPONSE_TYPE=code+id_token+token
  - RESPONSE_TYPE=code+token
